services:
  typescript:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ogp-dev-tool
    command: npm run watch
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
